import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Bell, Check, ChevronDown, Download, RotateCcw, SlidersHorizontal } from "lucide-react";
import { Button, CardLabel } from "@/components/ui";
import { defaultFilters, type DashboardFilters } from "@/components/dashboard/dashboardTypes";
const changeOptions = ["Urban", "Vegetation", "Mining", "Flood", "Water", "Wildfire", "Road", "Construction"];

export function FilterDrawer({ onApply }: { onApply: (filters: DashboardFilters) => void }) {
  const [open, setOpen] = useState(false); const [filters, setFilters] = useState(defaultFilters);
  const toggleType = (type: string) => setFilters((current) => ({ ...current, changeTypes: current.changeTypes.includes(type) ? current.changeTypes.filter((item) => item !== type) : [...current.changeTypes, type] }));
  return <div className="surface-card overflow-hidden rounded-card"><button onClick={() => setOpen((value) => !value)} aria-expanded={open} className="flex w-full items-center justify-between px-section py-4 text-left"><span className="flex items-center gap-2"><SlidersHorizontal size={16} className="text-primary"/><span className="text-button-label font-semibold text-text-primary">Advanced filters</span><span className="rounded-pill bg-primary/10 px-2 py-0.5 text-[10px] text-primary">{filters.changeTypes.length + (filters.confidence !== "All" ? 1 : 0)} active</span></span><ChevronDown size={16} className={`text-text-muted transition-transform ${open ? "rotate-180" : ""}`}/></button>
    <AnimatePresence initial={false}>{open && <motion.div initial={{height:0,opacity:0,y:-5}} animate={{height:"auto",opacity:1,y:0}} exit={{height:0,opacity:0,y:-4}} transition={{duration:.28,ease:[.22,1,.36,1]}} className="overflow-hidden"><div className="grid grid-cols-1 gap-5 border-t border-hairline px-section py-5 md:grid-cols-2 xl:grid-cols-4">
      <label className="space-y-2"><CardLabel>Date Range</CardLabel><select value={filters.dateRange} onChange={(e)=>setFilters({...filters,dateRange:e.target.value})} className="h-9 w-full rounded-control border border-hairline-strong bg-surface px-2 text-meta text-text-primary"><option>Jan – Jun 2025</option><option>Jul – Dec 2024</option><option>Jan – Dec 2024</option></select></label>
      <label className="space-y-2"><span className="flex justify-between"><CardLabel>Cloud Coverage</CardLabel><span className="text-meta text-text-primary">≤ {filters.cloud}%</span></span><input type="range" min="0" max="100" value={filters.cloud} onChange={(e)=>setFilters({...filters,cloud:Number(e.target.value)})} className="w-full accent-primary"/></label>
      <label className="space-y-2"><CardLabel>Satellite</CardLabel><select value={filters.satellite} onChange={(e)=>setFilters({...filters,satellite:e.target.value})} className="h-9 w-full rounded-control border border-hairline-strong bg-surface px-2 text-meta text-text-primary">{["Sentinel-1","Sentinel-2","Landsat"].map((item)=><option key={item}>{item}</option>)}</select></label>
      <label className="space-y-2"><CardLabel>Resolution</CardLabel><select value={filters.resolution} onChange={(e)=>setFilters({...filters,resolution:e.target.value})} className="h-9 w-full rounded-control border border-hairline-strong bg-surface px-2 text-meta text-text-primary">{["10m","20m","30m"].map((item)=><option key={item}>{item}</option>)}</select></label>
      <fieldset className="md:col-span-2"><legend><CardLabel>Change Type</CardLabel></legend><div className="mt-2 flex flex-wrap gap-2">{changeOptions.map((item)=><button type="button" key={item} onClick={()=>toggleType(item)} aria-pressed={filters.changeTypes.includes(item)} className={`rounded-pill border px-2.5 py-1 text-meta ${filters.changeTypes.includes(item)?"border-primary/60 bg-primary/15 text-text-primary":"border-hairline text-text-muted hover:text-text-primary"}`}>{item}</button>)}</div></fieldset>
      <label className="space-y-2"><CardLabel>Confidence</CardLabel><select value={filters.confidence} onChange={(e)=>setFilters({...filters,confidence:e.target.value})} className="h-9 w-full rounded-control border border-hairline-strong bg-surface px-2 text-meta text-text-primary">{["All","Low","Medium","High"].map((item)=><option key={item}>{item}</option>)}</select></label>
      <label className="space-y-2"><span className="flex justify-between"><CardLabel>Area Threshold</CardLabel><span className="text-meta text-text-primary">{filters.area} km²</span></span><input type="range" min="0" max="100" value={filters.area} onChange={(e)=>setFilters({...filters,area:Number(e.target.value)})} className="w-full accent-primary"/></label>
    </div><div className="flex justify-end gap-2 border-t border-hairline px-section py-3"><Button variant="secondary" onClick={()=>{setFilters(defaultFilters);onApply(defaultFilters);}}><RotateCcw size={14}/> Reset filters</Button><Button onClick={()=>{onApply(filters);setOpen(false);}}><Check size={14}/> Apply filters</Button></div></motion.div>}</AnimatePresence>
  </div>;
}

export function ExportMenu({ onExport }: { onExport: (format: string) => void }) {
  const [open,setOpen]=useState(false);
  return <div className="relative"><Button variant="secondary" aria-expanded={open} onClick={()=>setOpen((v)=>!v)}><Download size={15}/> Export <ChevronDown size={13}/></Button><AnimatePresence>{open&&<motion.div initial={{opacity:0,y:-6,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-5,scale:.98}} transition={{duration:.18,ease:"easeOut"}} style={{transformOrigin:"top right"}} className="absolute right-0 top-full z-30 mt-2 w-44 overflow-hidden rounded-control border border-hairline bg-surface p-1 shadow-elevation-3">{["PDF","PNG","CSV","JSON","TXT Summary"].map((format,index)=><motion.button key={format} initial={{opacity:0,x:5}} animate={{opacity:1,x:0}} transition={{delay:index*.025,duration:.16}} onClick={()=>{onExport(format);setOpen(false);}} className="w-full rounded-control px-3 py-2 text-left text-meta text-text-primary hover:bg-white/[0.07]">Export as {format}</motion.button>)}</motion.div>}</AnimatePresence></div>;
}

export function NotificationCenter() {
  const [open,setOpen]=useState(false);
  const notifications=["New satellite available · Sentinel-2", "Processing completed · AOI scan", "Cloud coverage high · 24%", "Analysis finished · 3 regions updated", "No changes detected · monitored region"];
  return <div className="relative"><Button variant="ghost" size="icon" aria-label="Notifications, 3 unread" aria-expanded={open} onClick={()=>setOpen((v)=>!v)} className="dashboard-tooltip relative" data-tooltip="Notifications"><Bell size={17}/><span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-rose-400 ring-2 ring-canvas"/></Button><AnimatePresence>{open&&<motion.div initial={{opacity:0,y:-8,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-6,scale:.98}} transition={{duration:.2,ease:"easeOut"}} style={{transformOrigin:"top right"}} className="absolute right-0 top-full z-30 mt-2 w-[min(20rem,calc(100vw-2rem))] rounded-card border border-hairline bg-surface p-3 shadow-elevation-3"><div className="mb-2 flex items-center justify-between px-1"><CardLabel>Notifications</CardLabel><span className="rounded-pill bg-rose-400/15 px-2 py-0.5 text-[10px] text-rose-300">3 unread</span></div>{notifications.map((item,index)=><motion.div key={item} initial={{opacity:0,x:8}} animate={{opacity:1,x:0}} transition={{delay:index*.035,duration:.18}} className="flex gap-2 border-t border-hairline px-1 py-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${index<3?"bg-primary":"bg-transparent"}`}/><p className="text-meta text-text-primary">{item}</p></motion.div>)}</motion.div>}</AnimatePresence></div>;
}
